version: '3'

services:
  web:
    depends_on:
      - api
    build: ./web
    image: web
    container_name: web
    networks:
      - transcendence-network
    restart: unless-stopped
    ports:
      - "8080:8080"

  api:
    build: ./api
    image: api
    container_name: api
    networks:
      - transcendence-network
    restart: unless-stopped
    ports:
      - "3000:3000"
    
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

networks:
  transcendence-network:
    driver: bridge