name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
      
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push api
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: transcendence42/api:latest
      -
        name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_API_HOST: ${{ secrets.VITE_API_HOST }}
          envkey_VITE_API_PORT: ${{ secrets.VITE_API_PORT }}
          envkey_VITE_GAME_NAMESPACE: ${{ secrets.VITE_GAME_NAMESPACE }}
          envkey_VITE_REDIRECT_LOGIN_URL: ${{ secrets.VITE_REDIRECT_LOGIN_URL }}
          directory: ./web
          
        
      -
        name: Build and push web
        uses: docker/build-push-action@v3
        with:
          context: ./web
          push: true
          tags: transcendence42/web:latest

  continuous-deployment:
    needs: [continuous-integration]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ubuntu/app
          command: bash production.sh

      # Catch SSM outputs
      - name: Get the outputs
        run: echo "THe command id is ${{ steps.ssm.outputs.command-id }}"
