name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: ./src/
